### ISSUE TITLE
Events Refresh Button Never Unblocks For Stopped App

### ISSUE THREAD

**Issue by jcscottiii** [18F/cg-deck#117]
Only in the case when navigating to an app page for an app in the STOPPED state, the event's refresh button never unblocks

![image](https://cloud.githubusercontent.com/assets/7788930/9914905/20b48f30-5c82-11e5-8e3d-dfd580712c44.png)

**Comment by brittag** [comment]
Closing this since this doesn't happen in the new codebase for the staging Dashboard.
