### ISSUE TITLE
Remove bootstrap CSS and classes from all code

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#172]
In order for developers to not have to deal with unused CSS code AND to improve performance of the app, bootstrap CSS should be removed from the app and dependencies, AND there should be no bootstrap classes in the components.

Acceptance criteria
- [ ] Bootstrap should not be in the bundled CSS output file
- [ ] Bootstrap should not be a dependency in `npm`
- [ ] None of the components should have bootstrap classes in their `className` attribute.

**Comment by jeremiak** [comment]
Hey @msecret I think this should've been closed with 242

**Comment by msecret** [comment]
I put it into awaiting acceptance.

**Comment by jeremiak** [comment]
Oh right, I forgot that PRs can get merged and then their original cards go to awaiting acceptance. Good call
