### ISSUE TITLE
UI: Refactor code that allows UI deck user to remove user from org

### ISSUE THREAD

**Issue by mogul** [18F/cg-deck#180]
In order to easily manage their organization an organization manager should be able to remove a user from the organization through the deck.

Acceptance Criteria

- [] GIVEN an org O AND a active user OM with OrgManager role on O AND an active user OU with OrgMember on O WHEN OM navigates to the organization user list for O THEN OM should see a button to remove OU from the organization
- [] GIVEN an org O AND a active user OM with OrgManager role on O AND an active user OU with OrgMember on O AND OU does not have any associations with O spaces WHEN they click the remove button on the dialog THEN the user is removed from the OUL.

Screen Shot 2015-12-16 at 12.13.09 PM.png (https://18f.aha.io:443/attachments/token/8b9323140f89abec0578e0cdad63af9bdf4fe576b1f24df3cb4a0b75d3805f90.download)

**Comment by mogul** [comment]
Refer back to comments on [the original story in Trello](https://trello.com/c/V1UZQYAS/390-ui-refactor-code-that-allows-ui-deck-user-to-remove-user-from-org).

**Comment by msecret** [comment]
This was completed in new dashboard.
