### ISSUE TITLE
UI: Refactor adding a service plan to a space in the deck

### ISSUE THREAD

**Issue by mogul** [18F/cg-deck#181]
In order to use a service in a space an org manager should be able to create a new service instance from the marketplace page in the deck UI.

- [] GIVEN org manager OM AND org O AND space S AND O has service SV available in the marketplace MP AND SV has service plan SP WHEN OM navigates to MP THEN OM should see a link to add SP to S.
- [] GIVEN org manager OM and org O and space S and O has a service SV available in the marketplace MP AND SV has a service plan SP WHEN OM adds SP to S THEN OM should see SV under Service instances list in S.

**Comment by mogul** [comment]
Refer back to comments on [the original story in Trello](https://trello.com/c/C87OIUan/428-ui-refactor-adding-a-service-plan-to-a-space-in-the-deck).

**Comment by msecret** [comment]
This was completed in new dashbaord
