### ISSUE TITLE
Add Javascript code linting

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#182]
In order for developers to write code in a consistent style, there should be a decided upon coding style guide with linting tools and configuration.

Files that are currently failing linting should be added to a lintignore file that will ensure the linter doesn't error for them.

Acceptance criteria
- [x] A developer should be able to find what Javascript style guide is the standard in the CONTRIBUTING document.
- [x] The automated tests should not pass if a file is not linted.
- [x] A developer should be able to see specific output on why their linting failed, including file and file number.
- [x] A developer should be able to add linting to a file by removing the file from a lint ignore file.

**Comment by msecret** [comment]
Screenshot of test command failing with information on files and line number.

![screen shot 2016-04-12 at 4 27 37 pm](https://cloud.githubusercontent.com/assets/1701077/14478523/74e7e794-00cb-11e6-8a41-e50163e74c5a.png)

**Comment by msecret** [comment]
AC1 is dependent on https://github.com/18F/cg-deck/pull/189

**Comment by jeremiak** [comment]
All criteria have been met with #176 and #189 has also been closed.
