### ISSUE TITLE
Document coding standards and workflow in contributing document

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#188]
In order for developers to write code in a consistent manner based on best practices, there should be a document specifying the coding style guide and linting tools setup as part of the build process.

#### Acceptance criteria
- [x] Build process automatically runs linting process when running main build (or tests?) and fails the build or tests if there are linting errors.
- [x] There's documentation in CONTRIBUTING about what style guides are in use.

**Comment by jeremiak** [comment]
Lint command runs (and fails appropriately) with tests since dc0b43f2cfa227c73c19c1045423c2f0f6d5f27e
Contribution document changes made in #189

**Comment by jeremiak** [comment]
@msecret why was this reopened?
