### ISSUE TITLE
Org page shows quota/usage

### ISSUE THREAD

**Issue by mogul** [18F/cg-deck#195]

**Comment by msecret** [comment]
Would this story be blocked by higher level changes to how we're calculating quota and usage, such as https://trello.com/c/pdUdOwoy/662-easily-generate-usage-based-billing-data?

Also, I'm confused why we'd want a separate app for showing billing data rather then just putting it in the deck. Seems like it'd be more work to create another app.

**Comment by mogul** [comment]
If it was about billing data it would be blocked on that, yes. (Ostensibly that work is nearly done but you'll need to check with @jcscottiii, who picked up the work when Dan left.) However, this one is strictly about quota and usage, which we already have data for today:
![image](https://cloud.githubusercontent.com/assets/47762/14836558/f9107db0-0bc5-11e6-9191-89e30af19560.png)

The problem people have complained about in the past is that this doesn't give any units, so is kind of useless for making judgement calls about what the current state means.

**Comment by mogul** [comment]
Also, not sure where "create another app" is implied... The Trello card is about being able to generate billing data. There's a separate feature for [auto-generating estimates/invoices on a monthly/quarterly cadence](https://18f.aha.io/features/CGP-243) and another for bringing [live billing data in the deck](https://18f.aha.io/features/CGP-225).

**Comment by msecret** [comment]
Cool, thanks for clarification, that all makes sense.

**Comment by mogul** [comment]
Closing now, will replace/reopen as UX research dictates.
