### ISSUE TITLE
App page shows basic information about the app: name, state, status, last push, build pack, stack and disk limit.

### ISSUE THREAD

**Issue by mogul** [18F/cg-deck#220]
In order for a space manager to see each apps name and state about their app there should be an app page with basic information on the app.

Acceptance criteria
- [ ] GIVEN a space manager SM AND the space manager has space SA AND SA has an app A WHEN  SM visits the SA page THEN SM should see a link to the A page with the name of A.
- [ ] GIVEN a space manager SM AND the space manager has space SA AND SA has an app A WHEN SM clicks on the A link on the SA page THEN SM should see an app page for A with
  - [x] name of app
  - [x] app state (running, paused, etc)
  - [x] date of last push
  - [x] which build pack was used (can this be multiple?)
  - [ ] stack limit (?)
  - [ ] disk limit

**Comment by msecret** [comment]
Requires a design.

**Comment by msecret** [comment]
I actually think we can ignore the design on this story for now, waiting until a designer gets ramped up on the project. So the point of this story will be more to create an app page, link to it and show some basic information.

**Comment by msecret** [comment]
@jcscottiii I'm a little unsure of how to get the current memory/disk and the memory/disk limit that's currently on the app page. Do you happen to know where that is in the API?

**Comment by jcscottiii** [comment]
There are two APIs.
This API will give you the limits for an app regardless of what state it is in: https://apidocs.cloudfoundry.org/237/apps/get_app_summary.html

When the app is in started mode, you can the current levels: https://apidocs.cloudfoundry.org/237/apps/get_detailed_stats_for_a_started_app.html
