### ISSUE TITLE
Pin and shrink-wrap npm dependencies

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#233]
In order for developers to be confident the code base will run in any environment, `npm` dependencies should be pinned to a specific version, shrink-wrapped with `npm`.

Acceptance criteria
- [x] When downloading the project on a new computer, and running `npm install` the npm dependencies should always be the same.

**Comment by msecret** [comment]
It *may* be wise to upgrade react before accomplishing this, to ensure the codebase is relatively up to date before being shrunk-wrapped for the first time #177 .

**Comment by jeremiak** [comment]
@msecret I think the acceptance criteria on this have been met as of the merge of #239. Do you agree?

**Comment by msecret** [comment]
Yea. The acceptance criteria on this story would be really hard to screenshot or show, but both Jeremia and I have confirmed them.

**Comment by jeremiak** [comment]
:+1: closing then
