### ISSUE TITLE
Change JS promise code to use `then` and `catch`

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#235]

**Comment by jeremiak** [comment]
Acceptance criteria:
- [ ] Grepping the project for `done` should show no relevant results.
- [ ] Eliminate duplicated methods in `cf_api`
- [ ] Remove polyfill support for `.done()` [as in `cf_api.js`](https://github.com/18F/cg-deck/blob/staging-alpha/static_src/util/cf_api.js#L3)
- [ ] Every promise returning function in cf_api should catch errors using `.catch()`
