### ISSUE TITLE
Incorporate base cg styles

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#243]
In order for users of the deck to see a shared basic styling with the rest of cloud.gov products, the deck site should have the base styles (colors, fonts) applied to the site.

The design of the frontend won't be finished as this point, as bootstrap still has to be removed and we have to apply component styles.

Acceptance criteria
- [x] The colors on the site should be the same as cg-style
- [x] The fonts on the site should be the same as cg-style

**Comment by jeremiak** [comment]
@msecret why is this re-opened?

**Comment by msecret** [comment]
It was a mistake because I forgot to uncheck my acceptance criteria

**Comment by jeremiak** [comment]
@msecret was this reopening intentional?
