### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by afeld** [18F/cg-deck#250]
Steps to the issue (for me, at least):

1. Visit https://console.cloud.gov.
1. Click "Login".
1. Click "Authorize".

I then get back to login.cloud.gov, but am not signed in. Maybe due to this JS error?

![screen shot 2016-04-20 at 5 44 33 pm](https://cloud.githubusercontent.com/assets/86842/14691527/aed9609a-071f-11e6-913c-c71760e86af1.png)

I tried clearing my cookies for *.cloud.gov, and that didn't help. Thoughts?

**Comment by msecret** [comment]
It sounds like this was an intermittent problem as I haven't heard of any other problems. OK to close @afeld ?

**Comment by afeld** [comment]
Yep, worked for me just now.
