### ISSUE TITLE
Multiple users unable to see any of their organizations

### ISSUE THREAD

**Issue by afeld** [18F/cg-deck#251]
@ykhadilkar-rei @rossdakin @stvnrlly all ran into this issue.

![screen shot 2016-04-20 at 5 29 45 pm](https://cloud.githubusercontent.com/assets/86842/14691596/0c7b9146-0720-11e6-878d-fb3d852aa356.png)

**Comment by ykhadilkar-rei** [comment]
I can see my "Sandbox" organization now. Not sure what changed. 
![screen shot 2016-04-21 at 10 03 18 am](https://cloud.githubusercontent.com/assets/3237208/14711682/552b5e34-07a8-11e6-92da-234855ecc826.png)

**Comment by msecret** [comment]
It sounds like this was an intermittent problem as I haven't heard of any other problems. OK to close @afeld ?
