### ISSUE TITLE
Create modular, two-column complex table interface

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#253]
In order for org managers to cleanly view the various data in the deck app and for cloudgov developers to easily build interfaces for data there should be a system to show tables of cloud.gov data in responsive two column designs in a similar vein to the [community UI](https://ui.apps.cloud.gov/).

Acceptance criteria
- [ ] Tables should be styled in the WDS visual style.
- [ ] Tables should work in two column layouts on screens larger then 1000px (made that number up)
- [ ] Tables should scale down to one column on screens smaller then 800px.
- [ ] Tables should support clickable action icons, such as create and delete actions.
- [ ] Tables should support having multiple labels in one cell.
- [ ] Tables should support nesting as seen on the current marketplace page

**Comment by mogul** [comment]
Closing now, will replace/reopen as UX research dictates.
