### ISSUE TITLE
turning off permissions looks like it doesn't work 

### ISSUE THREAD

**Issue by gbinal** [18F/cg-deck#254]
If I've granted someone permissions to a cloud.gov space and I want to remove them, I would click on one of the `ON` toggles and expect it to switch to `OFF`, in the same fashion that it switched from `OFF` to `ON` when I first granted permissions.  But it appears to stay on `ON`, no matter how many times I click.  

If I refresh the page and return to this view, I'll see that it actually has switched the permission to `OFF`, but many people won't think to do that and will just think that they were unable to remove the permission.  

![screen shot 2016-04-28 at 2 14 33 pm](https://cloud.githubusercontent.com/assets/633088/14896481/f22b0f9c-0d4b-11e6-9d54-a2a203405c5c.png)

_On ^^^ screen, I cannot click to make an `ON` switch go to `OFF`._  

![screen shot 2016-04-28 at 2 18 24 pm](https://cloud.githubusercontent.com/assets/633088/14896511/1979ffa4-0d4c-11e6-9d73-4a85fd175d49.png)

_But if I then refresh the page and come back here, I see that the switch is now toggled._

**Comment by msecret** [comment]
This will be solved in the new API.
