### ISSUE TITLE
Use immutable data library in stores

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#256]
In order for developers to lose less time due to mutating state AND for an org manager to see deck views that render and perform faster the flux stores should use immutable.js data structures.

**Comment by msecret** [comment]
Basic idea of how this would work:

The `_data` array on each store would be an `Immutable.List`.

When changes to the data are made from store actions, `_data` would be updated through Immutable's `mergeDeep` or `updateIn` methods.

**Comment by jeremiak** [comment]
Acceptance criteria:
- [ ] Attempting to change a store's data from within a component is not allowed
