### ISSUE TITLE
List prioritized features and MVP for deck refactor

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#264]
In order for front end developers on the cg team to know what features should be work on first in the deck AND for cloud.gov deck users to have the most important features available to them, the "deck usability" stories should be prioritized based on user research.

**Comment by mogul** [comment]
I suggest you also consider which capabilities of the community UI already exist in `console.cloud.gov` and prioritize those stories and the minimal scaffolding necessary to support them.

**Comment by mogul** [comment]
Reparented the stories that were hanging off of this one onto #190; expect @vz3 to take ownership of some of this activity in the course of doing user research.

**Comment by mogul** [comment]
(and closing this one out as redundant)
