### ISSUE TITLE
Add analytics to deprecated deck

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#265]
In order for the cg team to understand what features of the deck are currently being used, there should be analytics for every page view and event.

Acceptance criteria
- [ ] Every page registers as a page view.

~~- [ ] Every major action that can be taken registers a GA Event.~~

**Comment by msecret** [comment]
@thisisdano, @juliaelman would analytics data on the current deck be worth the effort for design research?

**Comment by jeremiak** [comment]
Currently blocked by #356

**Comment by jeremiak** [comment]
Unblocked now after the merge.

**Comment by juliaelman** [comment]
@msecret in response to your comment on whether or not analytics on the current deck is worth the effort, my two cents is yes. If anything it will be good to see the difference in reporting from the current to the new design.

@thisisdano do you think there is there anything specific we'd like to track events for? 💭

**Comment by msecret** [comment]
I now see console.fr.cloud.gov in google analytics.

**Comment by msecret** [comment]
![image](https://cloud.githubusercontent.com/assets/1701077/16353320/5f57c4b2-3a2d-11e6-897b-8429062fa7c3.png)
