### ISSUE TITLE
Add view of events and logs in app page

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#289]
In order for developers to see information of what is happening in their app, there should be a UI element that shows data for events and logs from logs.cloud.gov

Acceptance criteria
MVP:
- [ ] There's links in the events and log sections of the app page which take the developer to the correct page on the logs.cloud.gov site.

Post-MVP:
- [ ] The relevant information from logs.cloud.gov is shown for events and logs on the app page (likely through the use of an iframe)

**Comment by msecret** [comment]
@jeremiak assigning you as this would be a good thing to look into next. I think it might be best to investigate Post-MVP first to see if it's feasible.

**Comment by jeremiak** [comment]
What is the "correct page" defined as? It sounds to me like clicking on the link would take you to the "Dashboard" view on logs.cloud.gov and all of the events would be filtered by that application's name. How far off the mark am I?

**Comment by jeremiak** [comment]
Also where should the link be exactly? This answer might be dependent on what is decided in #290

**Comment by msecret** [comment]
@jeremiak it should be close to where it is on the current console app page, below all the other information.

**Comment by msecret** [comment]
So I'm not great at using Kibana, but it would be the discover page filtered to the org, space and app, probably 24 hours. If you play around in Kibana, it will give you a URL for the pages you pull up.

@mogul do you know how to differ between events and logs in kibana? I'm having trouble figuring it out.

**Comment by jeremiak** [comment]
Cool, some preliminary investigating:

It looks like Kibana gives us some nice URLs to get around. For instance, to filter by app name we can just use 
```
https://logs.cloud.gov/app/kibana#/dashboard/App-Overview?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-15m,mode:quick,to:now))&_a=(filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:%5Blogs-app-%5DYYYY.MM.DD,key:'@source.app.name',negate:!f,value:<<APP_NAME_HERE>>),query:(match:('@source.app.name':(query:<<APP_NAME_HERE>>,type:phrase))))),options:(darkTheme:!f),panels:!((col:1,id:App-logs-by-type,panelIndex:1,row:1,size_x:9,size_y:2,type:visualization),(col:10,id:App-names,panelIndex:2,row:1,size_x:3,size_y:2,type:visualization),(col:1,columns:!('@level','@source.name','@source.app.name','@message'),id:app-all,panelIndex:3,row:3,size_x:12,size_y:7,sort:!('@timestamp',desc),type:search)),query:(query_string:(analyze_wildcard:!t,query:'*')),title:'App%20-%20Overview',uiState:(P-1:(spy:(mode:(fill:!f,name:!n))),P-2:(spy:(mode:(fill:!f,name:!n)))))
```

One problem is that if you aren't already authenticated with logs.cloud.gov, the redirect after logging in doesn't include this query string so it gives you the default Kibana dashboard with all logs from all applications

**Comment by msecret** [comment]
@jeremiak completely forgot this sorry.

I think there's ways to embed just one section of kibana into an iframe, like one graph, which we would want to use.

Re: the authentication problem: I'm inclined to not tackle that right now as it sounds like it could be pretty difficult. I wonder if there's a way to get data on how many of our users would run into a bug like this.

**Comment by mogul** [comment]
> One problem is that if you aren't already authenticated with logs.cloud.gov, the redirect after logging in doesn't include this query string so it gives you the default Kibana dashboard with all logs from all applications

I think if we add `logs.cloud.gov` to [the `autoapprove` section of the UAA config](https://github.com/cloudfoundry/uaa/blob/master/docs/Sysadmin-Guide.rst#clients), then anyone already logged into the console should not see an issue here... @cnelson can you look into making that change?

**Comment by mogul** [comment]
@msecret The default view when you log into `logs.cloud.gov` is showing you application logs. To see application events you need to hit this folder icon in the upper-right and open an alternate dashboard.
![image](https://cloud.githubusercontent.com/assets/47762/15593568/74c2e1ce-2362-11e6-83c5-bb724a7f2168.png) ...and pick `App - Events`.

**Comment by jeremiak** [comment]
Sounds great! I'm going to wait until #295 is merged and therefore the app page isn't changing before I get going here but it should just be a matter of getting logs.cloud.gov on the `autoapprove` list and then using the links as Kibana does a nice job of making state transferable through the URL.

**Comment by jeremiak** [comment]
@mogul Can you provide some background on when something would show up in events versus logs and what the difference is between the two?

Right now, when I follow your instructions above to filter by events I actually see no data

**Comment by mogul** [comment]
Logs are generated by an application, making noise about what it does, what requests it's getting, etc.

Events are events in Cloud Foundry, like someone pushing a new version of an app, an app crashing and getting restarted, etc.

If you're not seeing event data where you expect to, maybe check with @LinuxBozo to make sure we didn't break something.

**Comment by jeremiak** [comment]
It looks like embedding a Kibana view as an iFrame is pretty easy (Kibana actually generates links for us in the UI), but we first need to enable iframe embeds on the logs.cloud.gov servers.

See issue ^^
