### ISSUE TITLE
Add links to documentation for unimplemented actions on app page

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#294]
In order for deck users to know how to accomplish actions that were in a previous iteration of the deck, there should be links to documentation on how to complete actions with the CLI.

Acceptance criteria:
- [x] There should be a link on how to start/stop/reset the app, https://docs.cloudfoundry.org/devguide/deploy-apps/deploy-app.html (this is the best page I could find, although the instructions don't match up prefectly)
- [x] There should be a link to create/delete a route, https://docs.cloud.gov/apps/custom-domains/#application-routes
- [x] There should be a link on how to (un)bind a service, https://docs.cloud.gov/apps/managed-services/

**Comment by msecret** [comment]
- Bind/Unbind service: https://docs.cloud.gov/apps/managed-services/#bind-the-service-instance

**Comment by msecret** [comment]
Here's an example of what this text will look like:

To modify, create or delete a route, view [application routes](https://docs.cloud.gov/apps/custom-domains/#application-routes) for more information.

**Comment by msecret** [comment]
Because there is no Services view currently on the home page, we'll create a heading for it with just the link and link text under it.

**Comment by jeremiak** [comment]
Looks good as a temporary solution

**Comment by jeremiak** [comment]
This is complete and looks good. Nice work!

I realize that these links are a temporary measure and don't always match up perfectly (stopping/starting isn't really clear in that documentation) but we can always change it as we get better documentation and interactions.
