### ISSUE TITLE
Each page should have a one sentence description of what it is

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#302]
For example, right now it is confusing what the “Marketplace” view is and does.

**Comment by brittag** [comment]
This is partially done! There's a bit more in our [Dashboard copy drafting Google Drawing](https://docs.google.com/drawings/d/1a9WD7gXMyfj8qEr95NUMffUwz7S5qkJ8IYOhhw8AFuU/edit) - mainly the Marketplace page.

**Comment by brittag** [comment]
(I'm reassigning this to Marco since I believe my part of this is done.)

**Comment by jeremiak** [comment]
Current `master` looks like it has addressed all of the issues outlined in the google drawing document. Accepted.
