### ISSUE TITLE
Remove HappyFoxChat widget from console.cloud.gov

### ISSUE THREAD

**Issue by afeld** [18F/cg-deck#305]
Being able to bring up that chat box is convenient, but if we don't actually log into chat ever, seems more consistent to just direct them to the [Help](https://docs.cloud.gov/help/) page. Pretty sure HappyFox was never cleared for use by Infrastructure anyway, so probably for the best to just shut it down.

* [ ] Remove the HappyFox snippet
* [ ] Remove the Slack integration
* [ ] Close the account
* [ ] Ensure there's a signpost to direct them to normal support channels

/cc @mogul

**Comment by msecret** [comment]
As a side note: we haven't implemented HappyFoxChat on the new deck code.

**Comment by mogul** [comment]
Yes, we should remove it, but only so long as it's still clear to them where to go for help (eg ensure there's a highly visible link to [the page on support in the docs](https://docs.cloud.gov/help/)).

**Comment by msecret** [comment]
This was completed by with the new dashboard.
