### ISSUE TITLE
There should be no unauthenticated view of the deck

### ISSUE THREAD

**Issue by jeremiak** [18F/cg-deck#308]
A user should not see the deck if they are not authenticated. Instead, they should be redirected to the UAA login page, and redirected to the deck after a successful authentication.

Currently, there is an extra click just to get to the login screen, even though the logged out view of the deck provides no user value.

**Comment by dlapiduz** [comment]
I had a pull request a while ago for this: https://github.com/18F/cg-deck/pull/87.

Not sure if it still works or what.

**Comment by jeremiak** [comment]
I cherry picked @dlapiduz's code onto the `staging-alpha` branch and pushed to the [jk-force-authentication](https://github.com/18F/cg-deck/tree/jk-force-authentication) branch, but I am still able to see an unauthenticated home page in an Incognito window.

@jcscottiii or @dlapiduz - my Go foo isn't too strong, did I get everything? From my reading of the code I think this should work
