### ISSUE TITLE
Typography spacing on app page

### ISSUE THREAD

**Issue by jeremiak** [18F/cg-deck#311]
The typography spacing on the app page is a bit off, with the app title and section headings

Screenshot of current app page:
![Current app page](https://s3.amazonaws.com/f.cl.ly/items/163F2q343D3S2E0f043o/Screen%20Shot%202016-06-03%20at%201.49.47%20PM.png?v=8a677457)

**Comment by msecret** [comment]
In order for the user of the console to understand the information on the app page, the typography should  highlight the hierarchy.
