### ISSUE TITLE
Broken table layout on org user management page

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#312]
In order for users to correctly understand the tabular information on the org user management page, the information should be in correct tabular format.

Acceptance criteria:
- [x] All table headings are on the same row.
- [x] All associated data of table headings in the actual table should be on a single row and should match up with the columns of the table headings.

**Comment by juliaelman** [comment]
Is this issue different than this? https://github.com/18F/cg-deck/issues/304

**Comment by msecret** [comment]
I think it might be. If you [go here](https://console-staging.cloud.gov/#/org/48b3f8a1-ffe7-4aa8-8e85-94768d6bd250/spaces/b7e56bba-b01b-4c14-883f-2e6d15284b58/users) and ensure you're on the "All organization users" tab, then the table is broken in a different way then in #304. My guess was that there was something off with the tags in the HTML/JSX.

**Comment by msecret** [comment]
I found the issue:

The last `<th>` the header for "actions" is not nested in the `<tr>`, which is incorrect.

**Comment by jeremiak** [comment]
Looks awesome!

Before screenshot:
![Screenshot of broken tables](https://s3.amazonaws.com/f.cl.ly/items/282y242W1m3Y0V1N2G1Y/Screen%20Shot%202016-06-09%20at%2012.22.15%20PM.png?v=89c9e215)

After screenshot:
![Screenshot of fixed tables](https://s3.amazonaws.com/f.cl.ly/items/1P160o2H2h352x1w0E3U/Screen%20Shot%202016-06-09%20at%2012.22.40%20PM.png?v=8aa9e507)
