### ISSUE TITLE
Scan the deck for security vulnerabilities

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#321]
In order to provide the safest environment possible, scan the application with currently accepted security tools.

Acceptance criteria
- [x] There should be a link to a document with the security results that members of GSA can see.
- [x] Any valid problems should have issues made for them.

**Comment by msecret** [comment]
According to the [18f before you ship guide](https://pages.18f.gov/before-you-ship/security/dynamic-scanning/), [OWASP Zap](https://www.owasp.org/index.php/OWASP_Zed_Attack_Proxy_Project) is the best tool to use for this.

This tools should be run on the console-staging.cloud.gov url. Additionally, the Ajax spider should also be run due to the nature of the application being primarily front end with ajax requests.

Zap will have to configured to be authenticated with the app. This is currently an unknown as it's unknown how this will work with the new SAML authentication (SAML?).

**Comment by jeremiak** [comment]
@afeld Is it possible to use compliance viewer with applications that need authentication? I didn't see any instructions in https://github.com/18F/concourse-compliance-testing#adding-a-project

**Comment by afeld** [comment]
Afraid not, sorry! https://github.com/18F/before-you-ship/issues/158#issuecomment-224657815 Will have to run it manually to hit all of the pages beind auth.

**Comment by msecret** [comment]
Link to results: https://docs.google.com/a/gsa.gov/spreadsheets/d/1OWWjvQJvf2EnF1EzAGH1RKOGZxdwPCTRePRiSVndLwU/edit?usp=sharing

**Comment by jeremiak** [comment]
@msecret is there an epic or label for these issues? Part of the acceptance criteria is for issues to be opened for anything the scanner found

**Comment by msecret** [comment]
I actually didn't write any issues because I'm not sure anything the scanner found warrants attention

**Comment by msecret** [comment]
well besides that one thing we fixed already

**Comment by jeremiak** [comment]
Did we fix the `x-frame` header problem? That strikes me as among the more important

**Comment by jeremiak** [comment]
Re-reading the results document it is clear that the `x-frame` problem is only on the `favicon.ico` so its not a huge deal.

Accepted.
