### ISSUE TITLE
Add New Relic service and configuration for errors and performance metrics on console

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#323]
In order for cloud.gov maintainers to be alerted when the error rate is above a certain amount AND for cloud.gov developers to be aware of application performance, there should be New Relic enabled (Browser support) and correctly configured.

Acceptance criteria
- [x] The browser functionality in New Relic should be turned on due to this being a front end app.
- [x] Configuration should attempt to follow the [fisma ready conventions](https://github.com/fisma-ready/new-relic)
- ~~Alerts should go to at least one central email and #cloud-gov-liberator slack channel.~~
- [x] An alert should go out for error percentage > 5%.
- [x] An alert should occur for Apdex score <0.7.
- ~~An alert should be set for a custom metric for viewing the app page.~~

**Comment by msecret** [comment]
Question: how will the migration from the current console.cloud.gov url work for when we push this app to that URL?

**Comment by msecret** [comment]
@jcscottiii would there be any reason or benefit in adding New Relic APM to the go part of the app? New Relic recommends using APM along with Browser. I did find a [go plugin](https://rpm.newrelic.com/accounts/958521/plugins/directory/136)

**Comment by msecret** [comment]
@jcscottiii I noticed my env var that I set earlier disappeared, probably in a deploy, do I have to add this in https://github.com/18F/cg-deck/blob/staging-alpha/deploy/travis-vars-to-manifest.py to get it working? Are we completely replace the env vars on deploy?

**Comment by msecret** [comment]
I found an error in the cf-deck logs that related to new relic. It kinda looks like it worked but it did appear as an error which I didn't totally understand.

**Comment by msecret** [comment]
This is under "cloud.gov Deck" in the browser tab.

**Comment by jcscottiii** [comment]
@msecret let's pair on this

**Comment by msecret** [comment]
In terms of alerting, I decided to stick with the base new relic policies,  apdex <0.7, error rate > 5.0.

**Comment by jeremiak** [comment]
Looks good, I can see in the New Relic alert history that these alerts have gone out for this application.
