### ISSUE TITLE
There should be downtime alerting set up for console

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#324]
In order for the cloud.gov developer team to be aware of when the console is down there should be an alert notification when the console site is completely down.

This is suggested in the [18f before you ship monitoring guide](https://pages.18f.gov/before-you-ship/infrastructure/monitoring/).

Acceptance criteria:
- [x] A service should run regular checks against the first page of the site to check if it's up.
- ~~[ ] A service should run a more comprehensive test including logging in and setting a test users permissions.~~
- ~~[ ] If the site goes down for more then 1 hour, an alert should be sent to the #cloud-gov-liberator and #cloud-gov slack channels.~~
- [x] If the site goes down for more then 1 hour, an alert should be sent to an email address.
- [x] There should be at least one successful result in the New Relic -> Cloud Foundry account under the "cloud.gov deck" monitor.

**Comment by msecret** [comment]
Question: who should this send an email to as a backup to slack?

**Comment by msecret** [comment]
Issue created in devops repo: https://github.com/18F/Infrastructure/issues/645

**Comment by msecret** [comment]
Looking into New Relic Synthetics rather then pingdom as suggested by devops team.

**Comment by msecret** [comment]
After setting up a test monitor on New Relic Synthetics, I've determine that the 2nd and 3rd acceptance criteria are not possible due to 18F not having a paid New Relic Synthetics account set up. Normal Synthetics only allows alerting through email, and doesn't allow any sort of scripting for the check.

Will briefly look to see if buying Pro is an option.

**Comment by jeremiak** [comment]
@msecret based on the email you got earlier, this might be done

**Comment by jeremiak** [comment]
@msecret from what I can tell looking at [this recent incident](https://rpm.newrelic.com/accounts/907948/incidents/22005708) is that the alerts are only going to an aquillent support email. Do we have one we can use here? If not, let's make a google group for it

**Comment by msecret** [comment]
I've been using my own email, I think this depends on the rest of the cloud.gov team and what they want.

**Comment by jeremiak** [comment]
Looks good to me! We can implement the pagerduty component after we talk with James
