### ISSUE TITLE
Check if launching deck refactor would require a new ATO

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#326]
Will we need a new ATO for the deck refactor? @18F/ato 

According to the [18f before you ship ATO guide](https://pages.18f.gov/before-you-ship/ato/), a new ATO is  required if changes include:
- Encryption methodologies
- Administrative functionality within the application
- The kinds of information you store (e.g. personally identifiable information)

The new deck doesn't make any of these changes, and is just a front end system off an existing backend data system.

**Comment by afeld** [comment]
My guess is that it won't... @jezhumble @NoahKunin?

**Comment by NoahKunin** [comment]
Feel free to push large PRs to me if you worried something will come up, but I don't see any there, there. 

Go forth!
