### ISSUE TITLE
Implement versioned releases in the staging deck

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#329]
#In order for developers to have versioned snapshots of every deck release in production, the release process for the staging deck should be built around versioning.

Acceptance criteria
- [x] The current version of the deck should be tracked in package.json and a tag.
- [x] There should be a written up release process in RELEASE.md.
- [x] The deck should only be released to production under the `dashboard` host when a new tag is present which should correspond with the version number in package.json.
- [x] There should be a staging site deployed from the `staging` branch to the `dashboard-staging` host.
- [x] The deck should have any valid differences that have been committed to the current `master` branch.

Optional:
- [ ] The deck UI should include the version number somewhere for help in debugging.

**Comment by jeremiak** [comment]
Maybe let's start with `1.0.0` when we release the `staging-alpha` branch?

**Comment by msecret** [comment]
So logic here would be only deploy on tags. Should we also have a `staging` branch with a separate deploy to `console-staging`? It would be essentially what we have now but not `staging-alpha`. @jeremiak

**Comment by jeremiak** [comment]
Definitely, that's a great idea!

I don't think we need a prescribed pathway for the branches though. That is to say, I don't think we need to require things get merged to `staging` and then PRs happen from `staging` to `master`. I'd rather just be able to cut a branch from anywhere named `staging` and then force push that to Github and deploy that code. This way we have a secondary environment for doing anything we want including user testing and bug verification/replication. What do you think?

**Comment by msecret** [comment]
So whats the common dev flow? Work on a feature, deploy to `master`? If we need `staging` for a specific reason, then we update it with `master`, and then merge our code onto it?

I think that could work. Because `master` isn't auto-deployed, it can definitely serve as the main branch. Then we can use staging to test `master` before a deploy as well as one-off tasks. There could be a case where we need another branch for just user testing work, one that we'll be careful about pushing to to limit breaking things for user testing, but not sure we'll need that right away.

**Comment by jcscottiii** [comment]
we can modify the info for https://console-staging.cloud.gov/ping

**Comment by msecret** [comment]
Oh awesome James, I didn't even know about that.

**Comment by msecret** [comment]
Work here: #408

**Comment by jeremiak** [comment]
This looks done to me. We can add in the version number to the UI but that shouldn't hold this from being closed.
