### ISSUE TITLE
Simplify maintaining npm dependencies by updating npm version

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#331]
In order for staging deck maintainers to easily update, add, remove npm dependencies, npm should be on version > 3 so the npm commands automatically update the shrinkwrap file

- [x] Run the npm installation, build and tests with node version > 5.0 and npm > 3.0 and ensure it works.
- [x] Add a `.nvmrc` file with new node version.
- [x] The engines hash in `package.json` should reflect new node and npm version.
- [x] Remove `$TRAVIS_NODE_VERSION` env var from travis config, it should use the default nvmrc file now.
- [x] Write a new npm-shrinkwrap file to ensure everything is correct.

**Comment by msecret** [comment]
Background:

Every time we have to update our npm dependencies, including adding new ones, upgrading old ones, or deleting unnecessary ones, we usually have to delete our whole node_modules folder, install again due to the way shrinkwrap works. This process can take 5-10 minutes making maintaining dependencies a burden.

The newer version of npm (> 3.0) includes functionality to automatically change the npm shrinkwrap file eliminating the need to completely rebuild the node_modules folder. This could save 5-10 minutes for every time we have to modify a package.

This work should be taken on when we determine that we have to update packages enough times to justify the amount of time this work will take. So that would mean 5-10 minutes * times we have to update dependencies compared to time this story takes.

**Comment by msecret** [comment]
This npm upgrade changes the structure of the `node_modules` folder so could break any code that directly uses the node modules folder. Here is a list of potential places that would have to be investigated:

```
package.json:11:    "build": "npm run clean && node_modules/webpack/bin/webpack.js",
package.json:12:    "codecov": "cat ./coverage/coverage-final.json | ./node_modules/codecov.io/bin/codecov.io.js",
webpack.config.js:39:          path.resolve(__dirname, 'node_modules/cloudgov-style'),
webpack.config.js:68:    fallback: path.resolve(__dirname, 'node_modules')
```

**Comment by msecret** [comment]
I tried this and the build, the tests and using the site all seemed to work.

**Comment by jeremiak** [comment]
Looks good to me!
