### ISSUE TITLE
Marketplace page sometimes doesn't load after visiting other pages

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#347]
I found while using the console-staging deck, when I was clicking around various pages and returned to the Marketplace page, it would say "No services found".

**Comment by jeremiak** [comment]
This looks resolved by #354.

Acceptance criteria:
- [X] A user can navigate to the Marketplace, and then to a space page, and back to the Marketplace page successfully.
- [X] The second marketplace visit should load quickly with cached data from the initial load, before making a request for new data and re-rendering if needed.
