### ISSUE TITLE
Import styles from cloudgov-style.css instead of individual component css files

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#350]
In order for developers to quickly develop style from cg-style to components in the deck, CSS modules should not be used.

This issue was discussed as an action item in 5/15/2016 sprint review.

**Comment by jeremiak** [comment]
Acceptance criteria:

- [ ] One can style part of a react component with just a class from `cloudgov-style`
- [ ] CSS files are not imported directly into components
- [ ] Webpack css-loader is removed from the project
- [ ] The `createStyler` utility and tests have been removed

**Comment by msecret** [comment]
Something I've been thinking about for this one: what will this mean for outside contributors using the code for their own project (ie not cloud.gov styling). It might be good to do a quick test run of how that would be done without CSS modules.

**Comment by jeremiak** [comment]
New acceptance criteria to go with the new title:

- [ ] Only `cloudgov-style/css/cloudgov-style.css` should be imported into components

**Comment by jeremiak** [comment]
@msecret why was this moved back to in progress? It seems done to me

**Comment by msecret** [comment]
It's not Awating Acceptance until its viewable in a shared environment (master) so it had to be merged first.
