### ISSUE TITLE
Master branch deploy is broken

### ISSUE THREAD

**Issue by jeremiak** [18F/cg-deck#356]
Currently, Travis does not deploy the `master` branch to the production route (console.cloud.gov). This is because the `master` branch is set to deploy to our current staging space (`deck-stage`).

I think this is the offending bit of code in [`/deploy/travis_deploy.sh`](https://github.com/18F/cg-deck/blob/master/deploy/travis_deploy.sh#L12-L21)
```
if [ "$TRAVIS_BRANCH" == "master" ]
then
	CF_MANIFEST="manifests/manifest-master.yml"
	CF_SPACE="deck-stage"
elif [ "$TRAVIS_BRANCH" == "production" ]
then
	CF_MANIFEST="manifests/manifest-production.yml"
	CF_SPACE="deck-prod"
fi
```

We no longer have a `production` branch so we should adjust this script and remove the `manifest-production.yml` since that is also out of date.

**Comment by jeremiak** [comment]
Acceptance criteria:
- [ ] `master` branch should deploy to the `deck-prod` space and be available at https://console.cloud.gov

**Comment by jeremiak** [comment]
This got closed by the merge, but it actually needs to stay open to go through "Awaiting Acceptance"

**Comment by msecret** [comment]
Looks like it worked https://travis-ci.org/18F/cg-deck/builds/138121014
