### ISSUE TITLE
Determine customer support plan for deck.

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#379]

**Comment by msecret** [comment]
Should we have a way to route customer support emails about technical issues with the deck to the liberator team somehow?

@mogul, as you've been the main person dealing with customer support, I'll leave it to you to decide if we need this.

**Comment by mogul** [comment]
I don't see that we need a separate channel from the usual for support requests about the deck vs. anything else. But if you want to stick a reference to the GitHub issues or the repo more generically in the footer or something,  I'm fine with that.

**Comment by mogul** [comment]
(My philosophy is that we don't want the user to have to juggle more than one way to report a problem. If we can provide one way that lets them tag what kind of issue out is, fine, but we're not there yet.

**Comment by msecret** [comment]
Closing as unnecessary
