### ISSUE TITLE
Show loading state

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#383]
In order for a deck user to understand that they're data isn't loaded yet, they should see a loading indicator on the page.

Acceptance criteria
- [ ] They don't see contradictory information: no apps and then apps.
- [ ] The single loading indicator shows up somewhere consistent in the content section.
- [ ] The loading indicator goes away when it's confirmed that theres no data OR there is data that comes back.

**Comment by msecret** [comment]
Where should we place the spinner?

**Comment by msecret** [comment]
- Have empty state in content area, when event for getting info is fired, the entire content area will be taken over. As soon as that's done, it will render the non-loading state.
- The empty state is should be not appear before page load before loading state.
- We coudl play with it so we fire the event before that.
- If there is any data already, it won't do the loading spinner.
  - So first time on org, you might see flash of content.
- Prefer to give a loading thing and then give you an empty state.
- They are different states but compositie in visual sense. if it comes back and theres nothing, show empty state, if it comes back with something, show data.
- As long as it doesn't show contradictory info.

**Comment by jeremiak** [comment]
List of loading states to implement:

- [ ] When loading the apps for a space
- [ ] When loading the services for a space
- [ ] When loading any list of users for an organization/space
- [ ] When loading possible services in the Marketplace view
- [ ] When loading an app detail view

Any that I'm missing @msecret?

**Comment by msecret** [comment]
thinking of an example for the apps store:

```
function app() 
  appActions.fetch();
  appActions.fetchStats()

AppStore
on FETCH:
  this._data[loading] = true;

on RESV:
  this._data[loading] = false

AppPage.jsx
render()
  let content = (this.state.loading) ? <span class="spinner">loading</span> : <h4>No apps</h4>
  if (this.state.app) //data exists
    content = <stuff>
```

**Comment by msecret** [comment]
@vz3 @thisisdano are you guys going to be working on the spinner for this?

**Comment by jeremiak** [comment]
Ya, I think that makes a lot of sense for the first implementation @msecret. I'll try it out in the app page first and we can see if we like it

**Comment by jeremiak** [comment]
So I gave it [a go in the base store](https://github.com/18F/cg-deck/commit/6b4ddb66ccfa09e7bfd01255aa882ecabc4e97a3) but I ran into [a problem implementing the loading state in a view](https://github.com/18F/cg-deck/commit/029880457f5879088d7c30b019073b59ed0ef1cb). Namely, by only having one `fetching` attribute on each store, it makes it hard to build a view out of multiple requests because of timing.

Any ideas on how to change the implementation @msecret?

**Comment by msecret** [comment]
That code generally made sense to me, what happened in the UI? in terms of the app store, I think we can check that the basic data is there at least (`APP_FETCH`), and can let the other data load after.

I think we need a way of setting loading states for different data, but that requires a lot more design thought then I'd like to figure out right now. In terms of how the UI works, is this better then not having a loading state at all?

**Comment by jeremiak** [comment]
To document the conclusion, @msecret and I came to regarding ^^, we will only have one fetching attribute on each store. We will build larger `cfApi` functions and actions to encompass them so that the `.fetching` attribute can be set in one spot.

You can see the basic idea in 1876758f6196a1de1b93d00b736d00e378b6246a

**Comment by thisisdano** [comment]
@msecret Here's a spinner that could work (at least as a starting point): http://loading.io/loader/?use=eyJzaXplIjoyOSwic3BlZWQiOiIyIiwiY2JrIjoiI2ZmZmZmZiIsImMxIjoiI2ZmZmZmZiIsImMyIjoiIzJjM2U1MCIsImMzIjoiNjAiLCJ0eXBlIjoicmluZy1hbHQifQ==

**Comment by msecret** [comment]
Nice I'll like that one, we'll put it in later
