### ISSUE TITLE
I see "Remove User from Org" buttons where I don't have authorization to do that

### ISSUE THREAD

**Issue by brittag** [18F/cg-deck#396]
When I look at "All organization users" in the sandbox organization, I see "Remove User from Org" for the other people in the org, but I don't have authorization to remove them, so I'm mildly confused to see that series of buttons. I'd expect to just not see that button if I can't do that. :)

![screen shot 2016-06-24 at 5 49 59 pm](https://cloud.githubusercontent.com/assets/391313/16353829/4bce3dc8-3a36-11e6-8007-f9864d90bac2.png)

If I try clicking it, I get "You are not authorized to perform the requested action", which makes sense, although that error is in a place I might not notice:

![screen shot 2016-06-24 at 6 08 25 pm](https://cloud.githubusercontent.com/assets/391313/16353845/b0531606-3a36-11e6-83af-ed6701762bfe.png)

**Comment by brittag** [comment]
Related, I'm not sure why these permissions have checkboxes for me (under both "current space users" and "all organization users") - I can click the checkboxes but don't have a way to save changes, which is somewhat confusing.

**Comment by msecret** [comment]
@brittag I think the changes should save automatically, but we need more UI to express that. I think it's a separate issue.

**Comment by brittag** [comment]
Thanks, filed at https://github.com/18F/cg-deck/issues/409

**Comment by msecret** [comment]
@brittag do you suggest just removing the buttons, or is there anything else that has to be done with the UI?

**Comment by brittag** [comment]
To solve this bug, I suggest just removing the "remove" buttons for everyone who doesn't have permission to remove others.

I'd also suggest making error messages show up more visibly when they happen (for example, in red text and closer to the action you tried to perform), but that's a different problem and should be handled more generally at some point.

**Comment by brittag** [comment]
Status - this isn't a blocker for switchover as long as we communicate in copy that you might see buttons when you can't actually remove people.

**Comment by msecret** [comment]
The deprecated deck had a uaa codebase that could do things like get permissions for the org:

https://github.com/18F/cg-deck/blob/deprecated/static/app/uaa.js#L61

There also seems to be a `/uaa` route to get current user info:

https://github.com/18F/cg-deck/blob/deprecated/static/app/uaa.js#L33.

So it seems like we could 

```
return http.get('/uaa/userinfo').then(function (response) {
  // Store user data
  userInfoStorage = response;
  return response
}).then(function(userInfo) {
  http.get('/uaa/Users', {
    "userName": user.userName
  })
}).then(function(userGuid) {
  findUserPerms(userGuid, 'manage_organization');
});
```

Now we have the current user's guid, name and permissions. There should be a separate utility for the `uaa` calls, not cf_api. There might need to be a separate store for current user, or keep current user as another attribute on the UserStore.

**Comment by msecret** [comment]
In terms of where we keep this, we could have a `currentUser` attribute on the `UserStore` which would keep information on the current user of the deck. This would be updated with name, guid, permissions as you make requests in uaa and cf api.

**Comment by msecret** [comment]
```
{
  guid: 'mmmmm',
  user_name: 'marco',
  roles: {
    '$orgguid: ['org_manager', 'org_auditor'],
    '$spaceguid': ['space_manager']
  }
```

```
{
  guid: 'mmmmm',
  user_name: 'marco',
  roles: {
    'org_manager': ['$orgguida', '$orgguidb'],
    'space_developer': ['$spaceguida', '$spaceguidb']
  }
```

**Comment by msecret** [comment]
@brittag I took a try at this in #438. You can only see the remove button if you have the "org_manager" role. Should I also change the checkboxes if you don't have that role? I was thinking of changing them to something besides a checkbox because you shouldn't have control over them.

**Comment by brittag** [comment]
Thanks @msecret! People should only be able to click checkboxes if they have permission to change the roles. As a simple temporary improvement it could be fine to just display them as disabled/unclickable checkboxes.

**Comment by msecret** [comment]
K I'll look into that @brittag

**Comment by jeremiak** [comment]
Accepting & closing this issue
