### ISSUE TITLE
Add npm version to dashboard build information

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#401]
In order for the cloud.gov team to know what version of the deck is live and deployed, there should be a way to get the current version in package.json from a route.

**Comment by msecret** [comment]
We should probably use the `/ping` golang route for this.

**Comment by jeremiak** [comment]
@msecret this is done, no? I see it in https://dashboard.cloud.gov/ping

**Comment by jeremiak** [comment]
I think this is done but I know we wanted to make it more obvious in the UI. Did we open an issue for that one?

**Comment by msecret** [comment]
Oh good point, we can keep this open and add that has acceptance criteria?
