### ISSUE TITLE
Service instance creation and viewing bug

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#403]
When a user creates a service instance on the marketplace page, and then goes to the service instance page to see the created service instance, there's a bug due to incomplete information.

To reproduce:
- Go to any org -> marketplace.
- Create a "sql" or similar service instance.
- Give the instance any name that's memorable
- Assign the instance to any space you can view.
- After the instance is created (the create form disappears) go the to space you selected.
- Go to the service instances tab
- Observe that the service instance is not there and there is an error in the JS console.

**Comment by jeremiak** [comment]
Resolved.
