### ISSUE TITLE
Go test failures should fail the build

### ISSUE THREAD

**Issue by jmcarp** [18F/cg-deck#404]
Errors like this should fail the build (I assume!) but don't: https://travis-ci.org/18F/cg-deck/builds/140568911#L3636. @jcscottiii mentioned that `codecheck.sh` might be ignoring test exit codes and probably knows the solution already.

**Comment by msecret** [comment]
yea that's my fault, I wanted to turn some tests off because we needed to get some messaging out and the broken acceptance tests were blocking us. Speaking of which, I'm not quite sure why we're getting failures, weren't not actively developing the go code on this branch.

**Comment by msecret** [comment]
This was fixed by #414
