### ISSUE TITLE
Refreshing a space page sends me to the "login" page, even though I'm logged in

### ISSUE THREAD

**Issue by brittag** [18F/cg-deck#411]
If I go to a space page like this one:

![screen shot 2016-06-30 at 4 19 09 pm](https://cloud.githubusercontent.com/assets/391313/16507399/64241e68-3ede-11e6-83aa-5c42308e22c2.png)

And then refresh the page, I get a "login" page:

![screen shot 2016-06-30 at 4 21 20 pm](https://cloud.githubusercontent.com/assets/391313/16507452/af31eb88-3ede-11e6-842b-2d3272b26f1a.png)

This is confusing since I expected to still be on the space page, and since I'm actually still logged in. (If I click "login", I go to the overview page without needing to log in again.)

This happens when I'm viewing any of the "tabs" on a space page (apps, service instances, user management).

The Overview and Marketplace pages don't have this behavior. When I refresh them, they behave as expected - I get the page I was on.

**Comment by brittag** [comment]
Status - not a blocker for Dashboard switchover

**Comment by msecret** [comment]
I believe this was fixed here: https://github.com/18F/cg-deck/pull/425

**Comment by brittag** [comment]
This "apps" tab does seem to work as expected now - when I refresh, I get the same info!

The "service instances" tab seems to not quite work as expected yet - when I refresh (using my local test copy), I get "no service instances" instead of my expected list of service instances.

I'm not sure if the "user management" tab is working as expected, since the test copy has no data for "all organization users".

**Comment by jeremiak** [comment]
I'm going to close this because the issue was fixed. @brittag, I think the "service instances" issue you are reporting would be addressed by the fix for #448
