### ISSUE TITLE
Add dashboard status to status page

### ISSUE THREAD

**Issue by msecret** [18F/cg-deck#426]
In order for cloud.gov users to know the up status of the dashboard, and find more information when something isn't work, it's current status should be added to https://cloudgov.statuspage.io/.

**Comment by msecret** [comment]
@dlapiduz @mogul any idea how we could do this? I'm guessing we need credentials to add something?

**Comment by mogul** [comment]
Just took care of adding the component. We're on a statuspage account that only allows 10 team members, and we're using all of those. I'll see if we can free up one of the unused ones.

**Comment by mogul** [comment]
> We're on a statuspage account that only allows 10 team members, and we're using all of those. I'll see if we can free up one of the unused ones.

Did that, so I think we're good here!
