### ISSUE TITLE
Stopped app usage info says "MB out of MB" instead of "0 MB out of 0 MB"

### ISSUE THREAD

**Issue by brittag** [18F/cg-deck#434]
When I look at a stopped app on dashboard-master.cloud.gov, the memory usage and disk usage lines say "MB out of MB":

![screen shot 2016-07-06 at 4 21 26 pm](https://cloud.githubusercontent.com/assets/391313/16637679/b431ee1a-4395-11e6-8920-0ca15549136a.png)

This is confusing to me as a user since it's missing numbers - I'm guessing it should probably say "0 MB out of 0 MB".

This seems helpful to fix because users likely want to know with certainty whether their stopped apps are using any memory (since that affects their quota usage, which affects billing).

**Comment by msecret** [comment]
Acceptance critiera:
- [ ] The UI should say 0 MB.

**Comment by jeremiak** [comment]
I wonder if we should say additional context. Something like:
"Stopped apps do not use any memory"

Thoughts @brittag and @msecret?

**Comment by brittag** [comment]
That'd be nice as an enhancement if it's easy. Let's have it say:

* **Memory usage:** 0 MB. *Stopped apps don't use any memory.*
* **Disk usage:** 0 MB. *Stopped apps don't use any disk space.*

**Comment by jeremiak** [comment]
This looks good on `master`
