### ISSUE TITLE
No unit labels for memory numbers on org page

### ISSUE THREAD

**Issue by brittag** [18F/cg-deck#455]
On my org page, the "Total Development Memory" and "Total Production Memory" items have numbers without unit labels (MB / GB / etc). Not sure if this has always been the case or if this is a regression.

My account:
![screen shot 2016-07-08 at 12 20 39 pm](https://cloud.githubusercontent.com/assets/391313/16699040/680760b6-4506-11e6-9fc3-fb2b84e35c6d.png)

Local test:
![screen shot 2016-07-08 at 12 20 11 pm](https://cloud.githubusercontent.com/assets/391313/16699045/6c71441e-4506-11e6-88b2-61ac3d64a32a.png)

**Comment by msecret** [comment]
Acceptance criteria:
- [ ] The data in the column should have ` MB` after the unit.
