### ISSUE TITLE
Alphabetize sidebar's list of spaces within an org

### ISSUE THREAD

**Issue by brittag** [18F/cg-deck#480]
If you have access to lots of spaces (such as org admins who can see everyone's sandbox spaces), it's harder to find the space you want since the sidebar's list of spaces isn't in alphabetical order. Let's fix that. :D

**Comment by msecret** [comment]
Acceptance criteria:
- [ ] The list of spaces within an org should be alphabetized.

**Comment by msecret** [comment]
In terms of technical implementation, should we

a. Use the `order_by` param in the API to get orgs and spaces ordered by `name`.
- Less cycles worked on the app to sort lists.
- Not sure how this would work with spaces within an org, or if it would work at all.

b. Do an easy sort function when setting the state in the component
- Probably most cycles.
- Very configurable if we need different ordering.

c. Do an easy sort function when the data is received in the store.
- Middle of those points above.

**Comment by jeremiak** [comment]
I personally like the second option, even though it is a bit more work. The reason I like it is sort order is a display problem and components should be the arbiter of how things are displayed.

**Comment by msecret** [comment]
I say we start with second option, maybe putting the sorting function in a util. But yea I agree, the sorting in the case is for the display.

**Comment by jcscottiii** [comment]
I agree with the second option as well. Eventually being able to sort depending on different attributes besides alphabetically might come in handy and it'll be easy to add in there.

**Comment by jeremiak** [comment]
Closed with #483
